name: Deploy to Azure Web App

on:
  push:
    branches:
      - main # ou o nome do branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'  # ou a versão que você está usando

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet build

      - name: Publish the app
        run: |
          dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <nome-do-app-service>  # Nome do seu App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Defina o arquivo de publicação como segredo
          package: ./publish
